version: "3"
services:
  app:
    platform: linux/amd64
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    ports:
      - 127.0.0.1:8080:8080
    environment:
      DOCKER_HOST: http://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      DEBUG: "1"
    volumes:
      - docker_certs:/certs

  docker:
    platform: linux/amd64
    image: docker:20.10-dind
    privileged: true
    environment:
      DOCKER_TLS_CERT_DIR: /certs
    volumes:
      - docker_certs:/certs
      - ./sandbox:/sandbox

volumes:
  docker_certs:
